-- Database schema for PECC MVP
-- SQL Server compatible

CREATE TABLE Users (
    Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    Email NVARCHAR(320) NOT NULL UNIQUE,
    PasswordHash VARBINARY(256) NOT NULL,
    FullName NVARCHAR(200) NOT NULL,
    Company NVARCHAR(200) NULL,
    Phone NVARCHAR(50) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE TicketStatus (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(50) NOT NULL,
    CONSTRAINT UQ_TicketStatus_Name UNIQUE (Name)
);

INSERT INTO TicketStatus (Name) VALUES ('Recibido'), ('Análisis'), ('Acciones'), ('Cerrado');

CREATE TABLE Tickets_RMA (
    Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    CustomerId UNIQUEIDENTIFIER NOT NULL,
    Title NVARCHAR(200) NOT NULL,
    ProblemType NVARCHAR(100) NOT NULL,
    Description NVARCHAR(MAX) NOT NULL,
    Priority NVARCHAR(20) NOT NULL DEFAULT 'Media',
    StatusId INT NOT NULL REFERENCES TicketStatus(Id),
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_TicketsRMA_Users FOREIGN KEY (CustomerId) REFERENCES Users(Id)
);

CREATE TABLE RMA_Status_History (
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    TicketId UNIQUEIDENTIFIER NOT NULL,
    StatusId INT NOT NULL,
    ChangedBy UNIQUEIDENTIFIER NULL,
    ChangedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    Notes NVARCHAR(500) NULL,
    CONSTRAINT FK_RMAStatusHistory_Ticket FOREIGN KEY (TicketId) REFERENCES Tickets_RMA(Id),
    CONSTRAINT FK_RMAStatusHistory_Status FOREIGN KEY (StatusId) REFERENCES TicketStatus(Id),
    CONSTRAINT FK_RMAStatusHistory_User FOREIGN KEY (ChangedBy) REFERENCES Users(Id)
);

CREATE TABLE Surveys (
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    TicketId UNIQUEIDENTIFIER NOT NULL,
    Rating TINYINT NOT NULL CHECK (Rating BETWEEN 1 AND 5),
    Comments NVARCHAR(1000) NULL,
    SubmittedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_Surveys_Ticket FOREIGN KEY (TicketId) REFERENCES Tickets_RMA(Id)
);

CREATE TABLE Documents (
    Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    Name NVARCHAR(200) NOT NULL,
    Category NVARCHAR(100) NOT NULL,
    FilePath NVARCHAR(500) NOT NULL,
    Version NVARCHAR(50) NULL,
    PublishedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    IsActive BIT NOT NULL DEFAULT 1
);

-- Indexes to support tracking and search
CREATE INDEX IX_Tickets_RMA_Status ON Tickets_RMA(StatusId);
CREATE INDEX IX_RMA_Status_History_Ticket ON RMA_Status_History(TicketId);
CREATE INDEX IX_Surveys_Ticket ON Surveys(TicketId);
